<?php

namespace Database\Seeders;

use App\Models\Patient;
use Illuminate\Database\Seeder;

class PatientSeeder extends Seeder
{
    public function run(): void
    {
        $patients = [
            [
                'patient_name'        => 'Ahmad Hidayat',
                'admission_date'      => '2023-08-01',
                'discharge_date'      => null,
                'gender'              => 'Male',
                'birth'               => '1978-03-15',
                'id_card'             => '3273011503780001',
                'address'             => 'Jl. Merdeka No. 12, Bandung',
                'contact'             => '081211112222',
                'education'           => 'University',
                'occupation'          => 'Wiraswasta',
                'photo'               => null,
                'referred'            => 'RS Hasan Sadikin',
                'next_of_kin_name'    => 'Fatimah Hidayat',
                'relationship'        => 'Spouse',
                'next_of_kin_address' => 'Jl. Merdeka No. 12, Bandung',
                'next_of_kin_contact' => '081233334444',
            ],
            [
                'patient_name'        => 'Siti Aminah',
                'admission_date'      => '2023-08-02',
                'discharge_date'      => null,
                'gender'              => 'Female',
                'birth'               => '1956-07-22',
                'id_card'             => '3273012207560002',
                'address'             => 'Jl. Sudirman No. 45, Bandung',
                'contact'             => '082222223333',
                'education'           => 'High School',
                'occupation'          => 'Ibu Rumah Tangga',
                'photo'               => null,
                'referred'            => 'Puskesmas Coblong',
                'next_of_kin_name'    => 'Iwan Setiawan',
                'relationship'        => 'Child',
                'next_of_kin_address' => 'Jl. Sudirman No. 47, Bandung',
                'next_of_kin_contact' => '082244445555',
            ],
            [
                'patient_name'        => 'Rizki Pradipta',
                'admission_date'      => '2023-08-03',
                'discharge_date'      => null,
                'gender'              => 'Male',
                'birth'               => '1995-11-08',
                'id_card'             => '3273010811950003',
                'address'             => 'Jl. Dipatiukur No. 7, Bandung',
                'contact'             => '083333334444',
                'education'           => 'College',
                'occupation'          => 'Mahasiswa',
                'photo'               => null,
                'referred'            => 'IGD RS Telkom',
                'next_of_kin_name'    => 'Hendra Pradipta',
                'relationship'        => 'Parent',
                'next_of_kin_address' => 'Jl. Dipatiukur No. 7, Bandung',
                'next_of_kin_contact' => '083355556666',
            ],
            [
                'patient_name'        => 'Nur Fadilah',
                'admission_date'      => '2023-08-05',
                'discharge_date'      => null,
                'gender'              => 'Female',
                'birth'               => '1982-04-12',
                'id_card'             => '3273011204820004',
                'address'             => 'Jl. Cihampelas No. 33, Bandung',
                'contact'             => '084444445555',
                'education'           => 'University',
                'occupation'          => 'Guru',
                'photo'               => null,
                'referred'            => 'Klinik Pratama Sehat',
                'next_of_kin_name'    => 'Rahmat Fadilah',
                'relationship'        => 'Spouse',
                'next_of_kin_address' => 'Jl. Cihampelas No. 33, Bandung',
                'next_of_kin_contact' => '084466667777',
            ],
            [
                'patient_name'        => 'Bambang Suryanto',
                'admission_date'      => '2023-08-06',
                'discharge_date'      => null,
                'gender'              => 'Male',
                'birth'               => '1963-09-30',
                'id_card'             => '3273013009630005',
                'address'             => 'Jl. Pasteur No. 78, Bandung',
                'contact'             => '085555556666',
                'education'           => 'High School',
                'occupation'          => 'Pegawai Negeri Sipil',
                'photo'               => null,
                'referred'            => 'RS Borromeus',
                'next_of_kin_name'    => 'Sri Suryanto',
                'relationship'        => 'Spouse',
                'next_of_kin_address' => 'Jl. Pasteur No. 78, Bandung',
                'next_of_kin_contact' => '085577778888',
            ],
            [
                'patient_name'        => 'Dewi Anggraini',
                'admission_date'      => '2023-08-07',
                'discharge_date'      => null,
                'gender'              => 'Female',
                'birth'               => '1990-06-17',
                'id_card'             => '3273011706900006',
                'address'             => 'Jl. Sukajadi No. 21, Bandung',
                'contact'             => '086666667777',
                'education'           => 'College',
                'occupation'          => 'Karyawan Swasta',
                'photo'               => null,
                'referred'            => 'IGD RS Telkom',
                'next_of_kin_name'    => 'Rudi Anggraini',
                'relationship'        => 'Spouse',
                'next_of_kin_address' => 'Jl. Sukajadi No. 21, Bandung',
                'next_of_kin_contact' => '086688889999',
            ],
            [
                'patient_name'        => 'Wahyu Hidayatullah',
                'admission_date'      => '2023-08-08',
                'discharge_date'      => null,
                'gender'              => 'Male',
                'birth'               => '1974-02-25',
                'id_card'             => '3273012502740007',
                'address'             => 'Jl. Tubagus Ismail No. 50, Bandung',
                'contact'             => '087777778888',
                'education'           => 'Master',
                'occupation'          => 'Dosen',
                'photo'               => null,
                'referred'            => 'Puskesmas Sukasari',
                'next_of_kin_name'    => 'Ani Hidayatullah',
                'relationship'        => 'Spouse',
                'next_of_kin_address' => 'Jl. Tubagus Ismail No. 50, Bandung',
                'next_of_kin_contact' => '087799990000',
            ],
            [
                'patient_name'        => 'Rini Susanti',
                'admission_date'      => '2023-08-09',
                'discharge_date'      => null,
                'gender'              => 'Female',
                'birth'               => '1987-12-03',
                'id_card'             => '3273010312870008',
                'address'             => 'Jl. Ganesha No. 15, Bandung',
                'contact'             => '088888889999',
                'education'           => 'University',
                'occupation'          => 'Apoteker',
                'photo'               => null,
                'referred'            => 'IGD RS Telkom',
                'next_of_kin_name'    => 'Andi Susanti',
                'relationship'        => 'Spouse',
                'next_of_kin_address' => 'Jl. Ganesha No. 15, Bandung',
                'next_of_kin_contact' => '088800001111',
            ],
        ];

        foreach ($patients as $patient) {
            Patient::create($patient);
        }
    }
}
